language: objective-c
osx_image: xcode7.3
script:
 - xcodebuild -project ./Apple/SCLTFramework/SCLTFramework.xcodeproj -scheme SCLTFrameworkOSXTests test
 - xcodebuild -project ./Apple/SCLTFramework/SCLTFramework.xcodeproj -scheme SCLTFrameworkiOSTests test -destination 'platform=iOS Simulator,name=iPad Air,OS=latest'
 - xcodebuild -project ./Apple/SCLT.xcodeproj -scheme SCLTiOS-Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
 - xcodebuild -project ./Apple/SCLT.xcodeproj -scheme SCLTOSX-Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
